FROM node:alpine
ARG VERSION
ENV APP_VERSION=test.${VERSION:-v0}
RUN apk add --update curl && \
rm -rf /var/cache/apk/*
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY ./index.js ./
EXPOSE 3000

HEALTHCHECK --interval=10s --timeout=1s \
  CMD curl -f http://localhost:3000/ || exit 1

CMD [ "npm","start" ]


# docker build --build-arg VERSION=v123 -f Dockerfile_z2 -t lab5z2:v0 .

# docker run -h=myhostanme -d --name lab5z2 -p 3000:3000 lab5z2:v0

